services:
  - type: web
    name: doctor-queue-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: CI
        value: false
      - key: REACT_APP_API_URL
        value: https://your-backend-url.onrender.com
